<a href="https://colab.research.google.com/github/Andersonhp3/Reconhecimento-de-padroes/blob/main/banknote.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from scipy.stats import friedmanchisquare
from scipy.stats import wilcoxon

# **Importando base de dados**

In [ ]:
banknote = pd.read_csv('data_banknote_authentication.csv')
banknote

variancia  assimentria  curtose  entropia  classe
0       3.62160      8.66610  -2.8073  -0.44699       0
1       4.54590      8.16740  -2.4586  -1.46210       0
2       3.86600     -2.63830   1.9242   0.10645       0
3       3.45660      9.52280  -4.0112  -3.59440       0
4       0.32924     -4.45520   4.5718  -0.98880       0
...         ...          ...      ...       ...     ...
1367    0.40614      1.34920  -1.4501  -0.55949       1
1368   -1.38870     -4.87730   6.4774   0.34179       1
1369   -3.75030    -13.45860  17.5932  -2.77710       1
1370   -3.56370     -8.38270  12.3930  -1.28230       1
1371   -2.54190     -0.65804   2.6842   1.19520       1

[1372 rows x 5 columns]

In [ ]:
banknote.describe(include='all')

variancia  assimentria      curtose     entropia       classe
count  1372.000000  1372.000000  1372.000000  1372.000000  1372.000000
mean      0.433735     1.922353     1.397627    -1.191657     0.444606
std       2.842763     5.869047     4.310030     2.101013     0.497103
min      -7.042100   -13.773100    -5.286100    -8.548200     0.000000
25%      -1.773000    -1.708200    -1.574975    -2.413450     0.000000
50%       0.496180     2.319650     0.616630    -0.586650     0.000000
75%       2.821475     6.814625     3.179250     0.394810     1.000000
max       6.824800    12.951600    17.927400     2.449500     1.000000

In [ ]:
X  = banknote.iloc[:,0:4]
Y = banknote.iloc[:,4]
Y

0       0
1       0
2       0
3       0
4       0
       ..
1367    1
1368    1
1369    1
1370    1
1371    1
Name: classe, Length: 1372, dtype: int64

# **Utilizando StandardScaler**

In [ ]:
from sklearn.preprocessing import StandardScaler
X = StandardScaler().fit_transform(X)
X = pd.DataFrame(X)
X

0         1         2         3
0     1.121806  1.149455 -0.975970  0.354561
1     1.447066  1.064453 -0.895036 -0.128767
2     1.207810 -0.777352  0.122218  0.618073
3     1.063742  1.295478 -1.255397 -1.144029
4    -0.036772 -1.087038  0.736730  0.096587
...        ...       ...       ...       ...
1367 -0.009711 -0.097693 -0.660962  0.300996
1368 -0.641313 -1.158984  1.179023  0.730127
1369 -1.472357 -2.621646  3.759017 -0.754884
1370 -1.406693 -1.756471  2.552043 -0.043158
1371 -1.047122 -0.439822  0.298616  1.136464

[1372 rows x 4 columns]

In [ ]:
X.describe()

0             1             2             3
count  1.372000e+03  1.372000e+03  1.372000e+03  1.372000e+03
mean   4.633482e-16 -5.385229e-17  8.577525e-18 -1.359457e-17
std    1.000365e+00  1.000365e+00  1.000365e+00  1.000365e+00
min   -2.630737e+00 -2.675252e+00 -1.551303e+00 -3.502703e+00
25%   -7.765474e-01 -6.188189e-01 -6.899455e-01 -5.817379e-01
50%    2.197423e-02  6.771828e-02 -1.812706e-01  2.880644e-01
75%    8.402427e-01  8.338757e-01  4.135174e-01  7.553713e-01
max    2.249008e+00  1.879908e+00  3.836586e+00  1.733680e+00

# **Processamento com K-NN**

In [ ]:
banknote2 = pd.read_csv('data_banknote_authentication.csv')
X  = banknote2.iloc[:,0:4]
y = banknote2.iloc[:,4]
X_teste = X.iloc[1371]
X = X.drop(1371)
y_teste = y.iloc[1371]
y = y.drop(1371)
X_teste

variancia     -2.54190
assimentria   -0.65804
curtose        2.68420
entropia       1.19520
Name: 1371, dtype: float64

In [ ]:
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors=3)

knn.fit(X, y)
knn.predict(np.array(X_teste).reshape(1,-1))

array([1])

In [ ]:
dist, vizinhos = knn.kneighbors(np.array(X_teste).reshape(1,-1))
classes = []
for v in vizinhos:
    classes.append(banknote2.iloc[:,4][v])
classes

[1005    1
 1036    1
 1188    1
 Name: classe, dtype: int64]

In [ ]:
y_teste

1

# **Processamento com Naive Bayes**

In [ ]:
banknote2 = pd.read_csv('data_banknote_authentication.csv')

X  = banknote2.iloc[:,0:4]
y = banknote2.iloc[:,4]
X = StandardScaler().fit_transform(X)
X = pd.DataFrame(X)
X_teste = X.iloc[1371]
X = X.drop(1371)
y_teste = y.iloc[1371]
y = y.drop(1371)

y_teste
X

0         1         2         3
0     1.121806  1.149455 -0.975970  0.354561
1     1.447066  1.064453 -0.895036 -0.128767
2     1.207810 -0.777352  0.122218  0.618073
3     1.063742  1.295478 -1.255397 -1.144029
4    -0.036772 -1.087038  0.736730  0.096587
...        ...       ...       ...       ...
1366 -1.000707  0.310376 -0.417731 -0.049348
1367 -0.009711 -0.097693 -0.660962  0.300996
1368 -0.641313 -1.158984  1.179023  0.730127
1369 -1.472357 -2.621646  3.759017 -0.754884
1370 -1.406693 -1.756471  2.552043 -0.043158

[1371 rows x 4 columns]

In [ ]:
from sklearn.naive_bayes import GaussianNB

gnb = GaussianNB()
gnb.fit(X, y)
gnb.predict(np.array(X_teste).reshape(1,-1))

array([1])

# **Processando com SVN**

In [ ]:
from sklearn.svm import SVC
svc = SVC(kernel='rbf')
svc.fit(X, y)
svc.predict(np.array(X_teste).reshape(1,-1))

array([1])

In [ ]:
svc = SVC(kernel='linear')
svc.fit(X, y)
svc.predict(np.array(X_teste).reshape(1,-1))

array([1])

In [ ]:
svc = SVC(kernel='poly')
svc.fit(X, y)
svc.predict(np.array(X_teste).reshape(1,-1))

array([1])

In [ ]:
svc = SVC(kernel='sigmoid')
svc.fit(X, y)
svc.predict(np.array(X_teste).reshape(1,-1))

array([1])

# **Processando com arvore de decisão**

In [ ]:
from sklearn.tree import DecisionTreeClassifier
arvore = DecisionTreeClassifier(criterion="entropy")
arvore.fit(X, y)
arvore.predict(np.array(X_teste).reshape(1,-1))

array([1])

In [ ]:
from sklearn.tree import export_text
tree_rules = export_text(arvore, feature_names=list(X.columns))
print(tree_rules)

|--- 0 <= -0.04
|   |--- 1 <= 0.67
|   |   |--- 2 <= 1.12
|   |   |   |--- 0 <= -0.28
|   |   |   |   |--- class: 1
|   |   |   |--- 0 >  -0.28
|   |   |   |   |--- 2 <= 0.28
|   |   |   |   |   |--- class: 1
|   |   |   |   |--- 2 >  0.28
|   |   |   |   |   |--- class: 0
|   |   |--- 2 >  1.12
|   |   |   |--- 1 <= -1.12
|   |   |   |   |--- 0 <= -0.28
|   |   |   |   |   |--- class: 1
|   |   |   |   |--- 0 >  -0.28
|   |   |   |   |   |--- class: 0
|   |   |   |--- 1 >  -1.12
|   |   |   |   |--- 2 <= 1.21
|   |   |   |   |   |--- 3 <= 0.20
|   |   |   |   |   |   |--- class: 0
|   |   |   |   |   |--- 3 >  0.20
|   |   |   |   |   |   |--- class: 1
|   |   |   |   |--- 2 >  1.21
|   |   |   |   |   |--- class: 0
|   |--- 1 >  0.67
|   |   |--- 0 <= -1.36
|   |   |   |--- 2 <= 0.17
|   |   |   |   |--- class: 1
|   |   |   |--- 2 >  0.17
|   |   |   |   |--- class: 0
|   |   |--- 0 >  -1.36
|   |   |   |--- class: 0
|--- 0 >  -0.04
|   |--- 0 <= 0.48
|   |   |--- 2 <= -0.85
|   |  

# **Processando com redes neurais**

In [ ]:
from sklearn.neural_network import MLPClassifier
mlp = MLPClassifier(activation="tanh")
mlp.fit(X, y)
mlp.predict(np.array(X_teste).reshape(1,-1))

/usr/local/lib/python3.7/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:571: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)


array([1])

In [ ]:
mlp = MLPClassifier(activation="logistic")
mlp.fit(X, y)
mlp.predict(np.array(X_teste).reshape(1,-1))

/usr/local/lib/python3.7/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:571: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)


array([1])

In [ ]:
mlp = MLPClassifier(activation="relu")
mlp.fit(X, y)
mlp.predict(np.array(X_teste).reshape(1,-1))

array([1])

In [ ]:
mlp = MLPClassifier(activation="identity", hidden_layer_sizes=(10,))
mlp.fit(X, y)
mlp.predict(np.array(X_teste).reshape(1,-1))

/usr/local/lib/python3.7/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:571: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)


array([1])

# **Avaliando com Holdout**

In [ ]:
from sklearn.model_selection import train_test_split
X_treino, X_teste, y_treino, y_teste = train_test_split(X, y, test_size=0.3, random_state=42)
X_treino

0         1         2         3
879  -0.352780 -0.086068 -0.655183  0.031928
783   0.014057  0.245129 -1.370334 -1.357670
605   0.222212  1.098679 -0.649426 -0.218662
1252 -1.105678 -1.491238  1.424238  0.848341
497  -0.169525 -0.601007  1.642808  0.927146
...        ...       ...       ...       ...
1095  0.256979  0.339301 -1.381475 -1.273918
1130 -0.959112 -1.564598  1.523067  1.005956
1294 -2.628731  1.256326 -0.285876 -1.594071
860  -1.370377  0.130861 -0.286872  0.080589
1126 -1.334377 -1.561769  2.331291  0.295454

[959 rows x 4 columns]

In [ ]:
mlp = MLPClassifier(activation="relu", hidden_layer_sizes=(10,))
mlp.fit(X_treino, y_treino)
mlp.predict(X_teste)

/usr/local/lib/python3.7/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:571: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)


array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0,
       1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0,
       1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0,
       0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1,
       1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1,
       1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0,
       1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0,
       0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1,
       1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1,
       0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1,
       1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1,
       0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0,

# **Avaliando com Kfold**

In [ ]:
from sklearn.model_selection import KFold
resultados = []
kf = KFold(n_splits=10, shuffle=True)
for index_treino, index_teste in kf.split(X):
    #X_treino, X_teste = X[index_treino], X[index_teste]
    #y_treino, y_teste = y[index_treino], y[index_teste]
    X_treino, X_teste = X.iloc[index_treino], X.iloc[index_teste]
    y_treino, y_teste = y.iloc[index_treino], y.iloc[index_teste]
    mlp.fit(X_treino, y_treino)
    resultados.append(mlp.predict(X_teste))
resultados

/usr/local/lib/python3.7/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:571: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)
/usr/local/lib/python3.7/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:571: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)
/usr/local/lib/python3.7/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:571: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)
/usr/local/lib/python3.7/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:571: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)


[array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1]),
 array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1]),
 array([0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 

# **Metricas**

In [ ]:
mlp = MLPClassifier(activation="relu", hidden_layer_sizes=(10,))
mlp.fit(X_treino, y_treino)
mlp.score(X_teste, y_teste)

/usr/local/lib/python3.7/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:571: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)


1.0

In [ ]:
from sklearn.metrics import precision_score, recall_score, f1_score
y_pred = mlp.predict(X_teste)

precision_score(y_teste, y_pred, average='macro')

1.0

In [ ]:
recall_score(y_teste, y_pred, average='macro')

1.0

In [ ]:
f1_score(y_teste, y_pred, average='macro')

1.0

# **Pratica do projeto**

**KNN**

In [ ]:
X_treino, X_teste, y_treino, y_teste = train_test_split(X, y, test_size=0.3, random_state=42)

valores_k = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]
resultados_knn = []

for k in valores_k:
    resultados_k = []
    knn = KNeighborsClassifier(n_neighbors=k)
    kf = KFold(n_splits=10, shuffle=True)
    for index_train, index_valid in kf.split(X_treino):
        X_train, X_validacao = X_treino.iloc[index_train], X_treino.iloc[index_valid]
        y_train, y_validacao = y_treino.iloc[index_train], y_treino.iloc[index_valid]
        knn.fit(X_train, y_train)
        resultados_k.append(knn.score(X_validacao, y_validacao))
    resultados_knn.append(sum(resultados_k)/len(resultados_k))
resultados_knn

[0.9979166666666668,
 0.9979057017543861,
 0.9979166666666666,
 0.9979166666666666,
 0.9979166666666668,
 0.9989583333333332,
 0.9979057017543859,
 0.9979166666666668,
 0.9968640350877195,
 0.9979166666666668,
 0.9927083333333334,
 0.9979166666666668,
 0.9927083333333334,
 0.9916557017543861,
 0.9906030701754387]

In [ ]:
knn = KNeighborsClassifier(n_neighbors=1)
knn.fit(X_treino, y_treino)
knn.score(X_teste, y_teste)

1.0

In [ ]:
y_pred = svc.predict(X_teste)

precision_score(y_teste, y_pred, average='macro')

1.0

In [ ]:
recall_score(y_teste, y_pred, average='macro')

0.9890710382513661

In [ ]:
f1_score(y_teste, y_pred, average='macro')

1.0

**SVM**

In [ ]:
valores_kernel = ["linear", "poly", "rbf", "sigmoid"]
resultados_svm = []

for kernel in valores_kernel:
    resultados_kernel = []
    svc = SVC(kernel=kernel)
    kf = KFold(n_splits=10, shuffle=True)
    for index_train, index_valid in kf.split(X_treino):
        X_train, X_validacao = X_treino.iloc[index_train], X_treino.iloc[index_valid]
        y_train, y_validacao = y_treino.iloc[index_train], y_treino.iloc[index_valid]
        svc.fit(X_train, y_train)
        resultados_kernel.append(svc.score(X_validacao, y_validacao))
    resultados_svm.append(sum(resultados_kernel)/len(resultados_kernel))
resultados_svm

[0.9832894736842105, 0.9854057017543859, 1.0, 0.7705921052631579]

In [ ]:
svc = SVC(kernel="rbf")
svc.fit(X_treino, y_treino)
svc.score(X_teste, y_teste)

1.0

In [ ]:
y_pred = svc.predict(X_teste)

precision_score(y_teste, y_pred, average='macro')

1.0

In [ ]:
recall_score(y_teste, y_pred, average='macro')

1.0

In [ ]:
f1_score(y_teste, y_pred, average='macro')

1.0

**MLP**

In [ ]:
valores_ativacao = ["identity", "logistic", "tanh", "relu"]
resultados_mlp = []

for ativacao in valores_ativacao:
    resultados_ativacao = []
    mlp = MLPClassifier(activation=ativacao)
    kf = KFold(n_splits=10, shuffle=True)
    for index_train, index_valid in kf.split(X_treino):
        X_train, X_validacao = X_treino.iloc[index_train], X_treino.iloc[index_valid]
        y_train, y_validacao = y_treino.iloc[index_train], y_treino.iloc[index_valid]
        mlp.fit(X_train, y_train)
        resultados_ativacao.append(svc.score(X_validacao, y_validacao))
    resultados_mlp.append(sum(resultados_ativacao)/len(resultados_ativacao))
resultados_mlp

/usr/local/lib/python3.7/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:571: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)
/usr/local/lib/python3.7/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:571: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)
/usr/local/lib/python3.7/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:571: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)
/usr/local/lib/python3.7/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:571: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)


[1.0, 1.0, 1.0, 1.0]

In [ ]:
#como os valores foram iguais/empataram escolhir um deles.para obter a curacia de..
mlp = MLPClassifier(activation="logistic")
mlp.fit(X_treino, y_treino)
mlp.score(X_teste, y_teste)


/usr/local/lib/python3.7/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:571: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)


0.9805825242718447

In [ ]:
y_pred = mlp.predict(X_teste)

precision_score(y_teste, y_pred, average='macro')

0.9795127748068925

In [ ]:
recall_score(y_teste, y_pred, average='macro')

0.9814350824444604

In [ ]:
f1_score(y_teste, y_pred, average='macro')

0.9803786165019646

**navebays**

In [ ]:
gnb = GaussianNB()
gnb.fit(X_treino, y_treino)
gnb.score(X_teste, y_teste)

0.837378640776699

In [ ]:
y_pred = gnb.predict(X_teste)

precision_score(y_teste, y_pred, average='macro')

0.8393329415221863

In [ ]:
recall_score(y_teste, y_pred, average='macro')

0.8306607488009163

In [ ]:
f1_score(y_teste, y_pred, average='macro')

0.8334851455285779

**Arvore**

In [ ]:
arvore = DecisionTreeClassifier(criterion="entropy")
arvore.fit(X_treino, y_treino)
arvore.score(X_teste, y_teste)

0.9878640776699029

In [ ]:
#precisão
y_pred = arvore.predict(X_teste)

precision_score(y_teste, y_pred, average='macro')

0.9886015325670499

In [ ]:
#recall
recall_score(y_teste, y_pred, average='macro')

0.986887632137829

In [ ]:
#f1-score
f1_score(y_teste, y_pred, average='macro')

0.9876899541659944