<a href="https://colab.research.google.com/github/Andersonhp3/Reconhecimento-de-padroes/blob/main/haberman2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
import Orange

## **Base com atributos numéricos**

In [ ]:
haberman = pd.read_csv('haberman.csv')
X = haberman.iloc[:,0:3] 
y= haberman.iloc[:,3]
X

age  year  nodes
0     30    64      1
1     30    62      3
2     30    65      0
3     31    59      2
4     31    65      4
..   ...   ...    ...
301   75    62      1
302   76    67      0
303   77    65      3
304   78    65      1
305   83    58      2

[306 rows x 3 columns]

In [ ]:
haberman.describe()

age        year       nodes       class
count  306.000000  306.000000  306.000000  306.000000
mean    52.457516   62.852941    4.026144    1.264706
std     10.803452    3.249405    7.189654    0.441899
min     30.000000   58.000000    0.000000    1.000000
25%     44.000000   60.000000    0.000000    1.000000
50%     52.000000   63.000000    1.000000    1.000000
75%     60.750000   65.750000    4.000000    2.000000
max     83.000000   69.000000   52.000000    2.000000

# **Utilizando StandardScale**

In [ ]:
from sklearn.preprocessing import StandardScaler
X = StandardScaler().fit_transform(X)
X = pd.DataFrame(X)
X

0         1         2
0   -2.082140  0.353584 -0.421592
1   -2.082140 -0.262921 -0.142959
2   -2.082140  0.661837 -0.560909
3   -1.989426 -1.187680 -0.282275
4   -1.989426  0.661837 -0.003642
..        ...       ...       ...
301  2.090018 -0.262921 -0.421592
302  2.182732  1.278342 -0.560909
303  2.275447  0.661837 -0.142959
304  2.368162  0.661837 -0.421592
305  2.831735 -1.495933 -0.282275

[306 rows x 3 columns]

# **Processamento com K-NN**

In [ ]:
haberman2 = pd.read_csv('haberman.csv')
X  = haberman2.iloc[:,0:3]
y = haberman2.iloc[:,3]
X_teste = X.iloc[305]
X = X.drop(305)
y_teste = y.iloc[305]
y = y.drop(305)
X_teste

age      83
year     58
nodes     2
Name: 305, dtype: int64

In [ ]:
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors=3)

knn.fit(X, y)
knn.predict(np.array(X_teste).reshape(1,-1))

array([1])

In [ ]:
dist, vizinhos = knn.kneighbors(np.array(X_teste).reshape(1,-1))
classes = []
for v in vizinhos:
    classes.append(haberman2.iloc[:,3][v])
classes

[304    2
 301    1
 303    1
 Name: class, dtype: int64]

In [ ]:
y_teste

2

# **Processamento com Naive Bayes**

In [ ]:
X  = haberman.iloc[:,0:3]
y = haberman.iloc[:,3]
X = StandardScaler().fit_transform(X)
X = pd.DataFrame(X)
X_teste = X.iloc[305]
X = X.drop(305)
y_teste = y.iloc[305]
y = y.drop(305)

y_teste

2

In [ ]:
from sklearn.naive_bayes import GaussianNB

gnb = GaussianNB()
gnb.fit(X, y)
gnb.predict(np.array(X_teste).reshape(1,-1))

array([1])

# **Processando com SVN**

In [ ]:
from sklearn.svm import SVC
svc = SVC(kernel='rbf')
svc.fit(X, y)
svc.predict(np.array(X_teste).reshape(1,-1))

array([1])

In [ ]:
svc = SVC(kernel='linear')
svc.fit(X, y)
svc.predict(np.array(X_teste).reshape(1,-1))

array([1])

In [ ]:
svc = SVC(kernel='poly')
svc.fit(X, y)
svc.predict(np.array(X_teste).reshape(1,-1))

array([1])

In [ ]:
svc = SVC(kernel='sigmoid')
svc.fit(X, y)
svc.predict(np.array(X_teste).reshape(1,-1))

array([1])

# **Processando com arvore de decisão**

In [ ]:
from sklearn.tree import DecisionTreeClassifier
arvore = DecisionTreeClassifier(criterion="entropy")
arvore.fit(X, y)
arvore.predict(np.array(X_teste).reshape(1,-1))

array([1])

In [ ]:
from sklearn.tree import export_text
tree_rules = export_text(arvore, feature_names=list(X.columns))
print(tree_rules)

|--- 2 <= 0.07
|   |--- 0 <= -1.11
|   |   |--- 2 <= -0.49
|   |   |   |--- 0 <= -1.66
|   |   |   |   |--- 1 <= -1.03
|   |   |   |   |   |--- class: 2
|   |   |   |   |--- 1 >  -1.03
|   |   |   |   |   |--- class: 1
|   |   |   |--- 0 >  -1.66
|   |   |   |   |--- 1 <= 0.82
|   |   |   |   |   |--- class: 1
|   |   |   |   |--- 1 >  0.82
|   |   |   |   |   |--- 0 <= -1.29
|   |   |   |   |   |   |--- class: 1
|   |   |   |   |   |--- 0 >  -1.29
|   |   |   |   |   |   |--- 1 <= 1.12
|   |   |   |   |   |   |   |--- class: 2
|   |   |   |   |   |   |--- 1 >  1.12
|   |   |   |   |   |   |   |--- class: 1
|   |   |--- 2 >  -0.49
|   |   |   |--- class: 1
|   |--- 0 >  -1.11
|   |   |--- 2 <= -0.49
|   |   |   |--- 0 <= -0.18
|   |   |   |   |--- 1 <= -0.42
|   |   |   |   |   |--- 0 <= -0.92
|   |   |   |   |   |   |--- 0 <= -1.02
|   |   |   |   |   |   |   |--- class: 1
|   |   |   |   |   |   |--- 0 >  -1.02
|   |   |   |   |   |   |   |--- 1 <= -1.34
|   |   |   |   |   |   |   |

# **Processando com redes neurais**

In [ ]:
from sklearn.neural_network import MLPClassifier
mlp = MLPClassifier(activation="tanh")
mlp.fit(X, y)
mlp.predict(np.array(X_teste).reshape(1,-1))

array([1])

In [ ]:
mlp = MLPClassifier(activation="logistic")
mlp.fit(X, y)
mlp.predict(np.array(X_teste).reshape(1,-1))

/usr/local/lib/python3.7/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:571: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)


array([1])

In [ ]:
mlp = MLPClassifier(activation="relu")
mlp.fit(X, y)
mlp.predict(np.array(X_teste).reshape(1,-1))

/usr/local/lib/python3.7/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:571: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)


array([1])

In [ ]:
mlp = MLPClassifier(activation="identity", hidden_layer_sizes=(10,))
mlp.fit(X, y)
mlp.predict(np.array(X_teste).reshape(1,-1))

array([1])

# **Avaliando com Holdout**

In [ ]:
from sklearn.model_selection import train_test_split
X_treino, X_teste, y_treino, y_teste = train_test_split(X, y, test_size=0.3, random_state=42)
X_treino

0         1         2
72  -0.876850  0.970090 -0.003642
15  -1.618567  0.045331 -0.560909
10  -1.711282 -0.879427 -0.421592
164  0.050296 -0.879427 -0.282275
224  0.699299  0.661837 -0.560909
..        ...       ...       ...
188  0.235725  1.894848  2.504056
71  -0.876850  0.661837 -0.560909
106 -0.505992  0.970090  1.110890
270  1.255586 -1.495933 -0.560909
102 -0.505992  1.278342 -0.560909

[213 rows x 3 columns]

In [ ]:
mlp = MLPClassifier(activation="relu", hidden_layer_sizes=(10,))
mlp.fit(X_treino, y_treino)
mlp.predict(X_teste)

/usr/local/lib/python3.7/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:571: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)


array([1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1,
       2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1])

# **Processando com Kfold**

In [ ]:
from sklearn.model_selection import KFold
resultados = []
kf = KFold(n_splits=10, shuffle=True)
for index_treino, index_teste in kf.split(X):
    X_treino, X_teste = X.iloc[index_treino], X.iloc[index_teste]
    y_treino, y_teste = y.iloc[index_treino], y.iloc[index_teste]
    mlp.fit(X_treino, y_treino)
    resultados.append(mlp.predict(X_teste))
resultados

/usr/local/lib/python3.7/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:571: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)
/usr/local/lib/python3.7/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:571: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)
/usr/local/lib/python3.7/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:571: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)
/usr/local/lib/python3.7/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:571: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)


[array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 2, 1, 2, 1, 1, 1, 1]),
 array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1]),
 array([2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1,
        2, 1, 1, 1, 1, 1, 1, 1, 1]),
 array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1]),
 array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1]),
 array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 2, 1, 1, 1, 1]),
 array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1]),
 array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 2, 1, 1, 1, 1, 1, 1]),
 array([1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        2, 1, 2, 1, 1, 1, 2, 1]),
 array([1, 1,

# **Metricas**

In [ ]:
mlp = MLPClassifier(activation="relu", hidden_layer_sizes=(10,))
mlp.fit(X_treino, y_treino)
mlp.score(X_teste, y_teste)

/usr/local/lib/python3.7/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:571: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)


0.5666666666666667

In [ ]:
from sklearn.metrics import precision_score, recall_score, f1_score
y_pred = mlp.predict(X_teste)

precision_score(y_teste, y_pred, average='macro')

0.7758620689655172

In [ ]:
recall_score(y_teste, y_pred, average='macro')

0.5357142857142857

In [ ]:
f1_score(y_teste, y_pred, average='macro')

0.4222222222222222

# **Pratica do projeto**

**KNN**

In [ ]:
X_treino, X_teste, y_treino, y_teste = train_test_split(X, y, test_size=0.3, random_state=42)

valores_k = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]
resultados_knn = []

for k in valores_k:
    resultados_k = []
    knn = KNeighborsClassifier(n_neighbors=k)
    kf = KFold(n_splits=10, shuffle=True)
    for index_train, index_valid in kf.split(X_treino):
        X_train, X_validacao = X_treino.iloc[index_train], X_treino.iloc[index_valid]
        y_train, y_validacao = y_treino.iloc[index_train], y_treino.iloc[index_valid]
        knn.fit(X_train, y_train)
        resultados_k.append(knn.score(X_validacao, y_validacao))
    resultados_knn.append(sum(resultados_k)/len(resultados_k))
resultados_knn

[0.6943722943722943,
 0.7467532467532468,
 0.7136363636363636,
 0.7606060606060605,
 0.7551948051948052,
 0.7612554112554114,
 0.7508658008658009,
 0.7651515151515151,
 0.7662337662337662,
 0.7599567099567099,
 0.7612554112554113,
 0.7649350649350648,
 0.7796536796536796,
 0.7551948051948052,
 0.7794372294372295]

In [ ]:
knn = KNeighborsClassifier(n_neighbors=8)
knn.fit(X_treino, y_treino)
knn.score(X_teste, y_teste)

0.7065217391304348

In [ ]:
y_pred = knn.predict(X_teste)

precision_score(y_teste, y_pred, average='macro')

0.6597560975609755

In [ ]:
recall_score(y_teste, y_pred, average='macro')

0.5717022441160372

In [ ]:
f1_score(y_teste, y_pred, average='macro')

0.5607427055702918

**SVM**

In [ ]:
valores_kernel = ["linear", "poly", "rbf", "sigmoid"]
resultados_svm = []

for kernel in valores_kernel:
    resultados_kernel = []
    svc = SVC(kernel=kernel)
    kf = KFold(n_splits=10, shuffle=True)
    for index_train, index_valid in kf.split(X_treino):
        X_train, X_validacao = X_treino.iloc[index_train], X_treino.iloc[index_valid]
        y_train, y_validacao = y_treino.iloc[index_train], y_treino.iloc[index_valid]
        svc.fit(X_train, y_train)
        resultados_kernel.append(svc.score(X_validacao, y_validacao))
    resultados_svm.append(sum(resultados_kernel)/len(resultados_kernel))
resultados_svm

[0.7463203463203463,
 0.7610389610389608,
 0.7692640692640692,
 0.7932900432900434]

In [ ]:
svc = SVC(kernel="rbf")
svc.fit(X_treino, y_treino)
svc.score(X_teste, y_teste)

0.717391304347826

In [ ]:
y_pred = svc.predict(X_teste)

precision_score(y_teste, y_pred, average='macro')

0.6823793490460157

In [ ]:
recall_score(y_teste, y_pred, average='macro')

0.5889436234263821

In [ ]:
f1_score(y_teste, y_pred, average='macro')

0.5847222222222223

**MLP**

In [ ]:
valores_ativacao = ["identity", "logistic", "tanh", "relu"]
resultados_mlp = []

for ativacao in valores_ativacao:
    resultados_ativacao = []
    mlp = MLPClassifier(activation=ativacao)
    kf = KFold(n_splits=10, shuffle=True)
    for index_train, index_valid in kf.split(X_treino):
        X_train, X_validacao = X_treino.iloc[index_train], X_treino.iloc[index_valid]
        y_train, y_validacao = y_treino.iloc[index_train], y_treino.iloc[index_valid]
        mlp.fit(X_train, y_train)
        resultados_ativacao.append(svc.score(X_validacao, y_validacao))
    resultados_mlp.append(sum(resultados_ativacao)/len(resultados_ativacao))
resultados_mlp

/usr/local/lib/python3.7/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:571: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)
/usr/local/lib/python3.7/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:571: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)
/usr/local/lib/python3.7/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:571: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)
/usr/local/lib/python3.7/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:571: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)


[0.8129870129870129,
 0.8127705627705627,
 0.8123376623376624,
 0.8127705627705628]

In [ ]:
#como os valores foram iguais/empataram escolhir um deles.para obter a curacia de..
mlp = MLPClassifier(activation="logistic")
mlp.fit(X_treino, y_treino)
mlp.score(X_teste, y_teste)


0.6956521739130435

In [ ]:
y_pred = mlp.predict(X_teste)

precision_score(y_teste, y_pred, average='macro')

0.6816479400749064

In [ ]:
recall_score(y_teste, y_pred, average='macro')

0.5265462506841817

In [ ]:
f1_score(y_teste, y_pred, average='macro')

0.47039473684210525

**navebays**

In [ ]:
gnb = GaussianNB()
gnb.fit(X_treino, y_treino)
gnb.score(X_teste, y_teste)

0.6956521739130435

In [ ]:
y_pred = gnb.predict(X_teste)

precision_score(y_teste, y_pred, average='macro')

0.6307519640852974

In [ ]:
recall_score(y_teste, y_pred, average='macro')

0.5637657361795293

In [ ]:
f1_score(y_teste, y_pred, average='macro')

0.5527777777777778

**Arvore**

In [ ]:
arvore = DecisionTreeClassifier(criterion="entropy")
arvore.fit(X_treino, y_treino)
arvore.score(X_teste, y_teste)

0.6630434782608695

In [ ]:
#precisão
y_pred = arvore.predict(X_teste)

precision_score(y_teste, y_pred, average='macro')

0.5327380952380952

In [ ]:
#recall
recall_score(y_teste, y_pred, average='macro')

0.5120415982484948

In [ ]:
#f1-score
f1_score(y_teste, y_pred, average='macro')

0.4756389042103327