<a href="https://colab.research.google.com/github/Andersonhp3/Reconhecimento-de-padroes/blob/main/tae2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import copy
from sklearn.metrics.cluster import v_measure_score
from sklearn import metrics
from sklearn.cluster import KMeans
from sklearn.metrics.pairwise import pairwise_distances,cosine_similarity
from sklearn.decomposition import PCA
from sklearn.preprocessing import StandardScaler
from sklearn.datasets import load_digits
from sklearn.preprocessing import OrdinalEncoder
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.svm import SVC
from sklearn.tree import DecisionTreeClassifier
from sklearn.tree import export_text
from sklearn import tree
from sklearn.neural_network import MLPClassifier
from sklearn.model_selection import train_test_split
from sklearn.model_selection import KFold
from sklearn.metrics import precision_score, recall_score, f1_score


## **Carregando base com atributos Numéricos e Categóricos**

In [ ]:
tae = pd.read_csv('tae.csv')

In [ ]:
tae.describe()

NEnglish  CourseInstr  ...   ClassSize       Class
count  151.000000   151.000000  ...  151.000000  151.000000
mean     1.807947    13.642384  ...   27.867550    2.019868
std      0.395225     6.825779  ...   12.893758    0.820327
min      1.000000     1.000000  ...    3.000000    1.000000
25%      2.000000     8.000000  ...   19.000000    1.000000
50%      2.000000    13.000000  ...   27.000000    2.000000
75%      2.000000    20.000000  ...   37.000000    3.000000
max      2.000000    25.000000  ...   66.000000    3.000000

[8 rows x 6 columns]

# **Utilizando one hot encoding**

In [ ]:
tae = pd.get_dummies(tae, columns=["NEnglish", "CourseInstr", "Course", "RegularSemest", "ClassSize"], prefix=["NEnglish", "CourseInstr", "Course", "RegularSemest", "ClassSize"])
tae

Class  NEnglish_1  NEnglish_2  ...  ClassSize_55  ClassSize_58  ClassSize_66
0        3           1           0  ...             0             0             0
1        3           0           1  ...             0             0             0
2        3           1           0  ...             0             0             0
3        3           1           0  ...             0             0             0
4        3           0           1  ...             1             0             0
..     ...         ...         ...  ...           ...           ...           ...
146      1           0           1  ...             0             0             0
147      1           0           1  ...             0             0             0
148      1           1           0  ...             0             0             0
149      1           0           1  ...             0             0             0
150      1           0           1  ...             0             0             0

[151 rows x 102 columns]

# **Padronizando com StandardScaler**

In [ ]:
from sklearn.preprocessing import StandardScaler
X = tae.iloc[:, 1:102]
Y = tae.iloc[:, 0]
X = StandardScaler().fit_transform(X)
X = pd.DataFrame(X)
X

0         1         2    ...       98        99       100
0    2.051072 -2.051072 -0.164957  ... -0.115857 -0.115857 -0.08165
1   -0.487550  0.487550 -0.164957  ... -0.115857 -0.115857 -0.08165
2    2.051072 -2.051072 -0.164957  ... -0.115857 -0.115857 -0.08165
3    2.051072 -2.051072 -0.164957  ... -0.115857 -0.115857 -0.08165
4   -0.487550  0.487550 -0.164957  ...  8.631338 -0.115857 -0.08165
..        ...       ...       ...  ...       ...       ...      ...
146 -0.487550  0.487550 -0.164957  ... -0.115857 -0.115857 -0.08165
147 -0.487550  0.487550 -0.164957  ... -0.115857 -0.115857 -0.08165
148  2.051072 -2.051072 -0.164957  ... -0.115857 -0.115857 -0.08165
149 -0.487550  0.487550 -0.164957  ... -0.115857 -0.115857 -0.08165
150 -0.487550  0.487550 -0.164957  ... -0.115857 -0.115857 -0.08165

[151 rows x 101 columns]

# **Avaliando com Holdout**

In [ ]:
from sklearn.model_selection import train_test_split
X_treino, X_teste, y_treino, y_teste = train_test_split(X, y, test_size=0.3, random_state=42)
X_treino

0         1         2    ...       98        99       100
109 -0.487550  0.487550 -0.164957  ... -0.115857 -0.115857 -0.08165
126  2.051072 -2.051072 -0.164957  ... -0.115857 -0.115857 -0.08165
75  -0.487550  0.487550 -0.164957  ... -0.115857 -0.115857 -0.08165
113 -0.487550  0.487550 -0.164957  ... -0.115857 -0.115857 -0.08165
65  -0.487550  0.487550 -0.164957  ... -0.115857 -0.115857 -0.08165
..        ...       ...       ...  ...       ...       ...      ...
71  -0.487550  0.487550 -0.164957  ... -0.115857 -0.115857 -0.08165
106 -0.487550  0.487550 -0.164957  ... -0.115857 -0.115857 -0.08165
14  -0.487550  0.487550 -0.164957  ... -0.115857 -0.115857 -0.08165
92  -0.487550  0.487550 -0.164957  ... -0.115857 -0.115857 -0.08165
102  2.051072 -2.051072 -0.164957  ... -0.115857 -0.115857 -0.08165

[105 rows x 101 columns]

In [ ]:
mlp = MLPClassifier(activation="relu", hidden_layer_sizes=(10,))
mlp.fit(X_treino, y_treino)
mlp.predict(X_teste)

/usr/local/lib/python3.7/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:571: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)


array([1, 2, 3, 3, 1, 1, 3, 2, 2, 2, 3, 1, 1, 3, 2, 2, 2, 1, 2, 3, 1, 1,
       2, 2, 2, 2, 1, 1, 1, 1, 2, 2, 2, 3, 1, 1, 1, 1, 1, 3, 1, 3, 3, 1,
       2, 3])

# **Processando com Kfold**

In [ ]:
from sklearn.model_selection import KFold
resultados = []
kf = KFold(n_splits=10, shuffle=True)
for index_treino, index_teste in kf.split(X):
    X_treino, X_teste = X.iloc[index_treino], X.iloc[index_teste]
    y_treino, y_teste = y.iloc[index_treino], y.iloc[index_teste]
    mlp.fit(X_treino, y_treino)
    resultados.append(mlp.predict(X_teste))
resultados

/usr/local/lib/python3.7/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:571: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)
/usr/local/lib/python3.7/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:571: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)
/usr/local/lib/python3.7/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:571: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)
/usr/local/lib/python3.7/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:571: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)


[array([3, 3, 2, 2, 3, 3, 2, 2, 1, 1, 1, 2, 3, 1, 2, 2]),
 array([2, 2, 2, 1, 3, 1, 1, 3, 1, 2, 1, 3, 3, 1, 2]),
 array([2, 2, 1, 2, 3, 2, 2, 2, 3, 2, 1, 2, 2, 1, 1]),
 array([3, 3, 2, 2, 1, 1, 3, 2, 2, 2, 1, 2, 1, 3, 1]),
 array([3, 3, 2, 3, 2, 1, 3, 3, 2, 3, 3, 2, 1, 1, 2]),
 array([3, 3, 3, 2, 2, 1, 3, 3, 2, 3, 2, 1, 1, 2, 1]),
 array([1, 1, 1, 3, 3, 2, 2, 2, 3, 1, 2, 2, 1, 1, 1]),
 array([3, 3, 3, 2, 2, 2, 1, 3, 3, 1, 3, 2, 1, 1, 1]),
 array([1, 2, 1, 1, 1, 1, 1, 2, 3, 3, 2, 1, 2, 2, 2]),
 array([3, 2, 1, 3, 3, 2, 2, 1, 1, 1, 3, 1, 3, 1, 3])]

# **Pratica do projeto**

**KNN**

In [ ]:
X_treino, X_teste, y_treino, y_teste = train_test_split(X, y, test_size=0.3, random_state=42)

valores_k = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]
resultados_knn = []

for k in valores_k:
    resultados_k = []
    knn = KNeighborsClassifier(n_neighbors=k)
    kf = KFold(n_splits=10, shuffle=True)
    for index_train, index_valid in kf.split(X_treino):
        X_train, X_validacao = X_treino.iloc[index_train], X_treino.iloc[index_valid]
        y_train, y_validacao = y_treino.iloc[index_train], y_treino.iloc[index_valid]
        knn.fit(X_train, y_train)
        resultados_k.append(knn.score(X_validacao, y_validacao))
    resultados_knn.append(sum(resultados_k)/len(resultados_k))
resultados_knn

[0.6036363636363636,
 0.5354545454545454,
 0.5427272727272727,
 0.4636363636363637,
 0.5327272727272727,
 0.47545454545454546,
 0.48454545454545456,
 0.4645454545454545,
 0.4790909090909091,
 0.42727272727272725,
 0.43090909090909096,
 0.4618181818181818,
 0.48090909090909106,
 0.4690909090909091,
 0.45636363636363636]

In [ ]:
knn = KNeighborsClassifier(n_neighbors=1)
knn.fit(X_treino, y_treino)
knn.score(X_teste, y_teste)

0.6739130434782609

In [ ]:
y_pred = knn.predict(X_teste)

precision_score(y_teste, y_pred, average='macro')

0.6802054154995331

In [ ]:
recall_score(y_teste, y_pred, average='macro')

0.6755952380952381

In [ ]:
f1_score(y_teste, y_pred, average='macro')

0.6745519713261648

**SVM**

In [ ]:
valores_kernel = ["linear", "poly", "rbf", "sigmoid"]
resultados_svm = []

for kernel in valores_kernel:
    resultados_kernel = []
    svc = SVC(kernel=kernel)
    kf = KFold(n_splits=10, shuffle=True)
    for index_train, index_valid in kf.split(X_treino):
        X_train, X_validacao = X_treino.iloc[index_train], X_treino.iloc[index_valid]
        y_train, y_validacao = y_treino.iloc[index_train], y_treino.iloc[index_valid]
        svc.fit(X_train, y_train)
        resultados_kernel.append(svc.score(X_validacao, y_validacao))
    resultados_svm.append(sum(resultados_kernel)/len(resultados_kernel))
resultados_svm

[0.6154545454545455,
 0.44818181818181824,
 0.45545454545454545,
 0.49818181818181817]

In [ ]:
svc = SVC(kernel="linear")
svc.fit(X_treino, y_treino)
svc.score(X_teste, y_teste)

0.6739130434782609

In [ ]:
y_pred = svc.predict(X_teste)

precision_score(y_teste, y_pred, average='macro')

0.6874879506458454

In [ ]:
recall_score(y_teste, y_pred, average='macro')

0.6785714285714285

In [ ]:
f1_score(y_teste, y_pred, average='macro')

0.6743295019157088

**MLP**

In [ ]:
valores_ativacao = ["identity", "logistic", "tanh", "relu"]
resultados_mlp = []

for ativacao in valores_ativacao:
    resultados_ativacao = []
    mlp = MLPClassifier(activation=ativacao)
    kf = KFold(n_splits=10, shuffle=True)
    for index_train, index_valid in kf.split(X_treino):
        X_train, X_validacao = X_treino.iloc[index_train], X_treino.iloc[index_valid]
        y_train, y_validacao = y_treino.iloc[index_train], y_treino.iloc[index_valid]
        mlp.fit(X_train, y_train)
        resultados_ativacao.append(svc.score(X_validacao, y_validacao))
    resultados_mlp.append(sum(resultados_ativacao)/len(resultados_ativacao))
resultados_mlp

/usr/local/lib/python3.7/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:571: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)
/usr/local/lib/python3.7/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:571: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)
/usr/local/lib/python3.7/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:571: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)
/usr/local/lib/python3.7/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:571: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)


[0.9718181818181819, 0.970909090909091, 0.9718181818181819, 0.9700000000000001]

In [ ]:
#como os valores foram iguais/empataram escolhir um deles.para obter a curacia de..
mlp = MLPClassifier(activation="identity")
mlp.fit(X_treino, y_treino)
mlp.score(X_teste, y_teste)


/usr/local/lib/python3.7/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:571: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)


0.6304347826086957

In [ ]:
y_pred = mlp.predict(X_teste)

precision_score(y_teste, y_pred, average='macro')

0.6303733031674209

In [ ]:
recall_score(y_teste, y_pred, average='macro')

0.6279761904761905

In [ ]:
f1_score(y_teste, y_pred, average='macro')

0.6287177328843996

**navebays**

In [ ]:
gnb = GaussianNB()
gnb.fit(X_treino, y_treino)
gnb.score(X_teste, y_teste)

0.6304347826086957

In [ ]:
y_pred = gnb.predict(X_teste)

precision_score(y_teste, y_pred, average='macro')

0.6489898989898991

In [ ]:
recall_score(y_teste, y_pred, average='macro')

0.625

In [ ]:
f1_score(y_teste, y_pred, average='macro')

0.6175308641975309

**Arvore**

In [ ]:
arvore = DecisionTreeClassifier(criterion="entropy")
arvore.fit(X_treino, y_treino)
arvore.score(X_teste, y_teste)

0.5869565217391305

In [ ]:
#precisão
y_pred = arvore.predict(X_teste)

precision_score(y_teste, y_pred, average='macro')

0.6238095238095238

In [ ]:
#recall
recall_score(y_teste, y_pred, average='macro')

0.5952380952380952

In [ ]:
#f1-score
f1_score(y_teste, y_pred, average='macro')

0.5866096866096866