<a href="https://colab.research.google.com/github/Andersonhp3/Reconhecimento-de-padroes/blob/main/tic_tac_toe2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import copy
from sklearn.metrics.cluster import v_measure_score
from sklearn import metrics
from sklearn.cluster import KMeans
from sklearn.metrics.pairwise import pairwise_distances,cosine_similarity
from sklearn.decomposition import PCA
from sklearn.preprocessing import StandardScaler
from sklearn.datasets import load_digits
from sklearn.preprocessing import OrdinalEncoder
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.svm import SVC
from sklearn.tree import DecisionTreeClassifier
from sklearn.tree import export_text
from sklearn import tree
from sklearn.neural_network import MLPClassifier
from sklearn.model_selection import train_test_split
from sklearn.model_selection import KFold
from sklearn.metrics import precision_score, recall_score, f1_score


## **Carregando base com atributos categóricos**


In [ ]:
TTT = pd.read_csv('tic-tac-toe.csv')

In [ ]:
TTT.describe(include="all")

tfs  tms  trs  mls  mds  mrs  bls  bms  brs     class
count   958  958  958  958  958  958  958  958  958       958
unique    3    3    3    3    3    3    3    3    3         2
top       x    x    x    x    x    x    x    x    x  positive
freq    418  378  418  378  458  378  418  378  418       626

# **Utilizando One Hot Enconder**

In [ ]:
TTT = pd.get_dummies(TTT, columns=["tfs", "tms", "trs", "mls", "mds", "mrs", "bls", "bms", "brs"], prefix=["tfs", "tms", "trs", "mls", "mds", "mrs", "bls", "bms", "brs"])
TTT
y = TTT.iloc[:, 0]
TTT

class  tfs_b  tfs_o  tfs_x  tms_b  ...  bms_o  bms_x  brs_b  brs_o  brs_x
0    positive      0      0      1      0  ...      1      0      0      1      0
1    positive      0      0      1      0  ...      0      1      0      1      0
2    positive      0      0      1      0  ...      1      0      0      0      1
3    positive      0      0      1      0  ...      0      0      1      0      0
4    positive      0      0      1      0  ...      1      0      1      0      0
..        ...    ...    ...    ...    ...  ...    ...    ...    ...    ...    ...
953  negative      0      1      0      0  ...      0      1      0      0      1
954  negative      0      1      0      0  ...      1      0      0      0      1
955  negative      0      1      0      0  ...      1      0      0      0      1
956  negative      0      1      0      0  ...      1      0      0      0      1
957  negative      0      1      0      0  ...      0      1      0      0      1

[958 rows x 28 columns]

In [ ]:
from sklearn.preprocessing import OrdinalEncoder  
atributo = ['class']
enc = OrdinalEncoder()
enc.fit(TTT[atributo])
TTT[atributo] = enc.transform(TTT[atributo])
y = TTT.iloc[:, 0]
y

0      1.0
1      1.0
2      1.0
3      1.0
4      1.0
      ... 
953    0.0
954    0.0
955    0.0
956    0.0
957    0.0
Name: class, Length: 958, dtype: float64

# **Padronização**


In [ ]:
from sklearn.preprocessing import StandardScaler
atributos = ["tfs_b","tfs_o","tfs_x","tms_b","tms_o","tms_x","trs_b","trs_o","trs_x","mls_b","mls_o","mls_x","mds_b","mds_o","mds_x","mrs_b","mrs_o","mrs_x","bls_b","bls_o","bls_x","bms_b","bms_o","bms_x","brs_b","brs_o","brs_x"]
X = StandardScaler().fit_transform(TTT[atributos])
X = pd.DataFrame(X)
X



0         1         2   ...        24        25        26
0   -0.52177 -0.733294  1.136603  ... -0.521770  1.363709 -0.879815
1   -0.52177 -0.733294  1.136603  ... -0.521770  1.363709 -0.879815
2   -0.52177 -0.733294  1.136603  ... -0.521770 -0.733294  1.136603
3   -0.52177 -0.733294  1.136603  ...  1.916552 -0.733294 -0.879815
4   -0.52177 -0.733294  1.136603  ...  1.916552 -0.733294 -0.879815
..       ...       ...       ...  ...       ...       ...       ...
953 -0.52177  1.363709 -0.879815  ... -0.521770 -0.733294  1.136603
954 -0.52177  1.363709 -0.879815  ... -0.521770 -0.733294  1.136603
955 -0.52177  1.363709 -0.879815  ... -0.521770 -0.733294  1.136603
956 -0.52177  1.363709 -0.879815  ... -0.521770 -0.733294  1.136603
957 -0.52177  1.363709 -0.879815  ... -0.521770 -0.733294  1.136603

[958 rows x 27 columns]

# **Avaliando com Holdout**

In [ ]:
X_treino, X_teste, y_treino, y_teste = train_test_split(X, y, test_size=0.3, random_state=42)
X_treino

0         1         2   ...       24        25        26
228 -0.52177 -0.733294  1.136603  ... -0.52177  1.363709 -0.879815
319 -0.52177  1.363709 -0.879815  ... -0.52177  1.363709 -0.879815
715 -0.52177 -0.733294  1.136603  ... -0.52177  1.363709 -0.879815
212 -0.52177 -0.733294  1.136603  ... -0.52177 -0.733294  1.136603
79  -0.52177 -0.733294  1.136603  ... -0.52177  1.363709 -0.879815
..       ...       ...       ...  ...      ...       ...       ...
106 -0.52177 -0.733294  1.136603  ... -0.52177 -0.733294  1.136603
270 -0.52177 -0.733294  1.136603  ... -0.52177 -0.733294  1.136603
860 -0.52177  1.363709 -0.879815  ... -0.52177 -0.733294  1.136603
435 -0.52177  1.363709 -0.879815  ... -0.52177 -0.733294  1.136603
102 -0.52177 -0.733294  1.136603  ... -0.52177  1.363709 -0.879815

[670 rows x 27 columns]

In [ ]:
mlp = MLPClassifier(activation="relu", hidden_layer_sizes=(10,))
mlp.fit(X_treino, y_treino)
mlp.predict(X_teste)

/usr/local/lib/python3.7/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:571: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)


array([1., 1., 1., 0., 0., 1., 1., 0., 1., 1., 1., 1., 1., 0., 1., 1., 1.,
       1., 0., 0., 0., 1., 0., 1., 0., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       0., 0., 1., 1., 1., 0., 1., 1., 0., 0., 1., 0., 1., 1., 0., 0., 0.,
       0., 1., 1., 1., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 0.,
       1., 1., 0., 1., 0., 0., 0., 1., 1., 0., 1., 0., 1., 1., 1., 1., 1.,
       1., 0., 0., 1., 1., 1., 1., 1., 0., 1., 1., 0., 1., 1., 1., 1., 1.,
       0., 1., 1., 1., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1., 0., 1., 0.,
       0., 1., 0., 0., 0., 1., 1., 0., 1., 0., 1., 1., 1., 0., 1., 0., 1.,
       1., 1., 0., 0., 1., 1., 1., 1., 0., 0., 1., 0., 1., 1., 1., 0., 1.,
       0., 1., 1., 0., 1., 0., 1., 0., 0., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 0., 0., 1., 1., 1., 0., 1., 1., 0., 1., 1., 0., 0., 1., 1., 1.,
       1., 0., 1., 0., 1., 1., 1., 1., 1., 1., 1., 1., 0., 1., 1., 1., 1.,
       0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0., 0., 0., 0., 1.,
       0., 1., 1., 0., 0.

# **Processando com Kfold**

In [ ]:
resultados = []
kf = KFold(n_splits=10, shuffle=True)
for index_treino, index_teste in kf.split(X):
    X_treino, X_teste = X.iloc[index_treino], X.iloc[index_teste]
    y_treino, y_teste = y.iloc[index_treino], y.iloc[index_teste]
    mlp.fit(X_treino, y_treino)
    resultados.append(mlp.predict(X_teste))
resultados

/usr/local/lib/python3.7/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:571: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)
/usr/local/lib/python3.7/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:571: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)
/usr/local/lib/python3.7/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:571: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)
/usr/local/lib/python3.7/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:571: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)


[array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 0., 1., 1., 0., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 1., 0., 0., 0., 0., 0., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 0., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 

# **Pratica do projeto**

**KNN**

In [ ]:
X_treino, X_teste, y_treino, y_teste = train_test_split(X, y, test_size=0.3, random_state=42)

valores_k = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]
resultados_knn = []

for k in valores_k:
    resultados_k = []
    knn = KNeighborsClassifier(n_neighbors=k)
    kf = KFold(n_splits=10, shuffle=True)
    for index_train, index_valid in kf.split(X_treino):
        X_train, X_validacao = X_treino.iloc[index_train], X_treino.iloc[index_valid]
        y_train, y_validacao = y_treino.iloc[index_train], y_treino.iloc[index_valid]
        knn.fit(X_train, y_train)
        resultados_k.append(knn.score(X_validacao, y_validacao))
    resultados_knn.append(sum(resultados_k)/len(resultados_k))
resultados_knn

[0.7776119402985076,
 0.7611940298507464,
 0.744776119402985,
 0.7417910447761195,
 0.7701492537313432,
 0.7895522388059703,
 0.835820895522388,
 0.8567164179104477,
 0.8820895522388058,
 0.9253731343283581,
 0.9283582089552238,
 0.9283582089552237,
 0.9,
 0.9,
 0.8582089552238805]

In [ ]:
knn = KNeighborsClassifier(n_neighbors=11)
knn.fit(X_treino, y_treino)
knn.score(X_teste, y_teste)

0.9027777777777778

In [ ]:
y_pred = knn.predict(X_teste)

precision_score(y_teste, y_pred, average='macro')

0.9366515837104072

In [ ]:
recall_score(y_teste, y_pred, average='macro')

0.8526315789473684

In [ ]:
f1_score(y_teste, y_pred, average='macro')

0.8797638217928073

**SVM**

In [ ]:
valores_kernel = ["linear", "poly", "rbf", "sigmoid"]
resultados_svm = []

for kernel in valores_kernel:
    resultados_kernel = []
    svc = SVC(kernel=kernel)
    kf = KFold(n_splits=10, shuffle=True)
    for index_train, index_valid in kf.split(X_treino):
        X_train, X_validacao = X_treino.iloc[index_train], X_treino.iloc[index_valid]
        y_train, y_validacao = y_treino.iloc[index_train], y_treino.iloc[index_valid]
        svc.fit(X_train, y_train)
        resultados_kernel.append(svc.score(X_validacao, y_validacao))
    resultados_svm.append(sum(resultados_kernel)/len(resultados_kernel))
resultados_svm

[0.9850746268656717,
 0.9850746268656716,
 0.9552238805970148,
 0.8074626865671644]

In [ ]:
svc = SVC(kernel="poly")
svc.fit(X_treino, y_treino)
svc.score(X_teste, y_teste)

0.9895833333333334

In [ ]:
y_pred = svc.predict(X_teste)

precision_score(y_teste, y_pred, average='macro')

0.9923469387755102

In [ ]:
recall_score(y_teste, y_pred, average='macro')

0.9842105263157894

In [ ]:
f1_score(y_teste, y_pred, average='macro')

0.9881225684945631

**MLP**

In [ ]:
valores_ativacao = ["identity", "logistic", "tanh", "relu"]
resultados_mlp = []

for ativacao in valores_ativacao:
    resultados_ativacao = []
    mlp = MLPClassifier(activation=ativacao)
    kf = KFold(n_splits=10, shuffle=True)
    for index_train, index_valid in kf.split(X_treino):
        X_train, X_validacao = X_treino.iloc[index_train], X_treino.iloc[index_valid]
        y_train, y_validacao = y_treino.iloc[index_train], y_treino.iloc[index_valid]
        mlp.fit(X_train, y_train)
        resultados_ativacao.append(svc.score(X_validacao, y_validacao))
    resultados_mlp.append(sum(resultados_ativacao)/len(resultados_ativacao))
resultados_mlp

/usr/local/lib/python3.7/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:571: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)
/usr/local/lib/python3.7/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:571: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)
/usr/local/lib/python3.7/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:571: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)
/usr/local/lib/python3.7/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:571: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)


[0.9910447761194028, 0.991044776119403, 0.991044776119403, 0.9910447761194028]

In [ ]:
#como os valores foram iguais/empataram escolhir um deles.para obter a curacia de..
mlp = MLPClassifier(activation="logistic")
mlp.fit(X_treino, y_treino)
mlp.score(X_teste, y_teste)


/usr/local/lib/python3.7/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:571: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)


0.9791666666666666

In [ ]:
y_pred = mlp.predict(X_teste)

precision_score(y_teste, y_pred, average='macro')

0.9849246231155779

In [ ]:
recall_score(y_teste, y_pred, average='macro')

0.968421052631579

In [ ]:
f1_score(y_teste, y_pred, average='macro')

0.9760425909494232

**navebays**

In [ ]:
gnb = GaussianNB()
gnb.fit(X_treino, y_treino)
gnb.score(X_teste, y_teste)

0.6597222222222222

In [ ]:
y_pred = gnb.predict(X_teste)

precision_score(y_teste, y_pred, average='macro')

0.6226385636221702

In [ ]:
recall_score(y_teste, y_pred, average='macro')

0.6285246795745841

In [ ]:
f1_score(y_teste, y_pred, average='macro')

0.6246808510638298

**Arvore**

In [ ]:
arvore = DecisionTreeClassifier(criterion="entropy")
arvore.fit(X_treino, y_treino)
arvore.score(X_teste, y_teste)

0.9340277777777778

In [ ]:
y_pred = arvore.predict(X_teste)

precision_score(y_teste, y_pred, average='macro')

0.9228249194414608

In [ ]:
recall_score(y_teste, y_pred, average='macro')

0.9293973275156804

In [ ]:
f1_score(y_teste, y_pred, average='macro')

0.9259730245268469