<a href="https://colab.research.google.com/github/Andersonhp3/Reconhecimento-de-padroes/blob/main/transfusion.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.metrics.cluster import v_measure_score
from sklearn import metrics
from sklearn.metrics.pairwise import pairwise_distances,cosine_similarity
from sklearn.preprocessing import StandardScaler
from sklearn.datasets import load_digits
from sklearn.preprocessing import OrdinalEncoder
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.svm import SVC
from sklearn.tree import DecisionTreeClassifier
from sklearn.tree import export_text
from sklearn import tree
from sklearn.neural_network import MLPClassifier
from sklearn.model_selection import train_test_split
from sklearn.model_selection import KFold
from sklearn.metrics import precision_score, recall_score, f1_score

# **Carregando Base**

In [ ]:
transfusion = pd.read_csv('transfusion.csv')
X = transfusion.iloc[:,0:4]
y= transfusion.iloc[:,4]
X

Recency  Frequency  Monetary  Time
0          2         50     12500    98
1          0         13      3250    28
2          1         16      4000    35
3          2         20      5000    45
4          1         24      6000    77
..       ...        ...       ...   ...
743       23          2       500    38
744       21          2       500    52
745       23          3       750    62
746       39          1       250    39
747       72          1       250    72

[748 rows x 4 columns]

# **Utilizando StandardScale**

In [ ]:
from sklearn.preprocessing import StandardScaler
X = StandardScaler().fit_transform(X)
X = pd.DataFrame(X)
X

0         1         2         3
0   -0.927899  7.623346  7.623346  2.615633
1   -1.175118  1.282738  1.282738 -0.257881
2   -1.051508  1.796842  1.796842  0.029471
3   -0.927899  2.482313  2.482313  0.439973
4   -1.051508  3.167784  3.167784  1.753579
..        ...       ...       ...       ...
743  1.667904 -0.602307 -0.602307  0.152621
744  1.420685 -0.602307 -0.602307  0.727324
745  1.667904 -0.430940 -0.430940  1.137826
746  3.645659 -0.773675 -0.773675  0.193671
747  7.724778 -0.773675 -0.773675  1.548328

[748 rows x 4 columns]

# **Avaliando com Holdout**

In [ ]:
from sklearn.model_selection import train_test_split
X_treino, X_teste, y_treino, y_teste = train_test_split(X, y, test_size=0.3, random_state=42)
X_treino

0         1         2         3
369  0.802637 -0.088204 -0.088204  0.234722
628 -0.927899 -0.088204 -0.088204  1.178876
235 -0.186241  0.768635  0.768635  1.178876
585 -0.927899 -0.773675 -0.773675 -1.325186
209  0.184588 -0.430940 -0.430940 -0.832584
..        ...       ...       ...       ...
71  -0.927899 -0.259572 -0.259572 -0.750483
106 -1.175118  0.425899  0.425899  1.014675
270  0.802637  0.940003  0.940003  0.234722
435  0.802637  0.254532  0.254532  2.410382
102 -0.680679  0.597267  0.597267  0.234722

[523 rows x 4 columns]

In [ ]:
mlp = MLPClassifier(activation="relu", hidden_layer_sizes=(10,))
mlp.fit(X_treino, y_treino)
mlp.predict(X_teste)

/usr/local/lib/python3.7/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:571: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)


array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0])

# **Processando com Kfold**

In [ ]:
from sklearn.model_selection import KFold
resultados = []
kf = KFold(n_splits=10, shuffle=True)
for index_treino, index_teste in kf.split(X):
    X_treino, X_teste = X.iloc[index_treino], X.iloc[index_teste]
    y_treino, y_teste = y.iloc[index_treino], y.iloc[index_teste]
    mlp.fit(X_treino, y_treino)
    resultados.append(mlp.predict(X_teste))
resultados

/usr/local/lib/python3.7/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:571: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)
/usr/local/lib/python3.7/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:571: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)
/usr/local/lib/python3.7/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:571: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)
/usr/local/lib/python3.7/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:571: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)


[array([1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
        1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0]),
 array([1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0]),
 array([1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0]),
 array([1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
 

# **Pratica do projeto**

**KNN**

In [ ]:
X_treino, X_teste, y_treino, y_teste = train_test_split(X, y, test_size=0.3, random_state=42)

valores_k = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]
resultados_knn = []

for k in valores_k:
    resultados_k = []
    knn = KNeighborsClassifier(n_neighbors=k)
    kf = KFold(n_splits=10, shuffle=True)
    for index_train, index_valid in kf.split(X_treino):
        X_train, X_validacao = X_treino.iloc[index_train], X_treino.iloc[index_valid]
        y_train, y_validacao = y_treino.iloc[index_train], y_treino.iloc[index_valid]
        knn.fit(X_train, y_train)
        resultados_k.append(knn.score(X_validacao, y_validacao))
    resultados_knn.append(sum(resultados_k)/len(resultados_k))
resultados_knn

[0.7017053701015966,
 0.7628809869375907,
 0.7647677793904208,
 0.7837082728592162,
 0.7821117561683598,
 0.7992017416545718,
 0.7895500725689405,
 0.7895863570391872,
 0.8033744557329461,
 0.7855950653120464,
 0.7915820029027577,
 0.7802975326560231,
 0.8050072568940493,
 0.7933599419448475,
 0.8009796806966618]

In [ ]:
knn = KNeighborsClassifier(n_neighbors=13)
knn.fit(X_treino, y_treino)
knn.score(X_teste, y_teste)

0.7377777777777778

In [ ]:
y_pred = knn.predict(X_teste)

precision_score(y_teste, y_pred, average='macro')

0.6438247712878256

In [ ]:
recall_score(y_teste, y_pred, average='macro')

0.5825757575757575

In [ ]:
f1_score(y_teste, y_pred, average='macro')

0.5868218743191509

**SVM**

In [ ]:
valores_kernel = ["linear", "poly", "rbf", "sigmoid"]
resultados_svm = []

for kernel in valores_kernel:
    resultados_kernel = []
    svc = SVC(kernel=kernel)
    kf = KFold(n_splits=10, shuffle=True)
    for index_train, index_valid in kf.split(X_treino):
        X_train, X_validacao = X_treino.iloc[index_train], X_treino.iloc[index_valid]
        y_train, y_validacao = y_treino.iloc[index_train], y_treino.iloc[index_valid]
        svc.fit(X_train, y_train)
        resultados_kernel.append(svc.score(X_validacao, y_validacao))
    resultados_svm.append(sum(resultados_kernel)/len(resultados_kernel))
resultados_svm

[0.7641571553994732, 0.7772827041264267, 0.7998463564530292, 0.731387181738367]

In [ ]:
svc = SVC(kernel="rbf")
svc.fit(X_treino, y_treino)
svc.score(X_teste, y_teste)

0.7297297297297297

In [ ]:
y_pred = svc.predict(X_teste)

precision_score(y_teste, y_pred, average='macro')

0.6588486140724947

In [ ]:
recall_score(y_teste, y_pred, average='macro')

0.5669362084456424

In [ ]:
f1_score(y_teste, y_pred, average='macro')

0.5595238095238095

**MLP**

In [ ]:
valores_ativacao = ["identity", "logistic", "tanh", "relu"]
resultados_mlp = []

for ativacao in valores_ativacao:
    resultados_ativacao = []
    mlp = MLPClassifier(activation=ativacao)
    kf = KFold(n_splits=10, shuffle=True)
    for index_train, index_valid in kf.split(X_treino):
        X_train, X_validacao = X_treino.iloc[index_train], X_treino.iloc[index_valid]
        y_train, y_validacao = y_treino.iloc[index_train], y_treino.iloc[index_valid]
        mlp.fit(X_train, y_train)
        resultados_ativacao.append(svc.score(X_validacao, y_validacao))
    resultados_mlp.append(sum(resultados_ativacao)/len(resultados_ativacao))
resultados_mlp

/usr/local/lib/python3.7/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:571: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)


[0.8024582967515365,
 0.8027655838454786,
 0.8027875329236174,
 0.8025241439859527]

In [ ]:
#como os valores foram iguais/empataram escolhir um deles.para obter a curacia de..
mlp = MLPClassifier(activation="tanh")
mlp.fit(X_treino, y_treino)
mlp.score(X_teste, y_teste)


0.7162162162162162

In [ ]:
y_pred = mlp.predict(X_teste)

precision_score(y_teste, y_pred, average='macro')

0.6142857142857143

In [ ]:
recall_score(y_teste, y_pred, average='macro')

0.5287511230907458

In [ ]:
f1_score(y_teste, y_pred, average='macro')

0.4946341463414634

**navebays**

In [ ]:
gnb = GaussianNB()
gnb.fit(X_treino, y_treino)
gnb.score(X_teste, y_teste)

0.7466666666666667

In [ ]:
y_pred = gnb.predict(X_teste)

precision_score(y_teste, y_pred, average='macro')

0.6850507982583455

In [ ]:
recall_score(y_teste, y_pred, average='macro')

0.5515151515151515

In [ ]:
f1_score(y_teste, y_pred, average='macro')

0.5339922241197631

**Arvore**

In [ ]:
arvore = DecisionTreeClassifier(criterion="entropy")
arvore.fit(X_treino, y_treino)
arvore.score(X_teste, y_teste)

0.6888888888888889

In [ ]:
#precisão
y_pred = arvore.predict(X_teste)

precision_score(y_teste, y_pred, average='macro')

0.5857142857142857

In [ ]:
#recall
recall_score(y_teste, y_pred, average='macro')

0.5757575757575758

In [ ]:
#f1-score
f1_score(y_teste, y_pred, average='macro')

0.5788770053475936